/**
 * F-1 golden fixtures — relay replay of the NaCl subset the server uses.
 *
 * Replays the frozen fixture generated by mobile
 * (`mobile/src/crypto/__tests__/fixtures/f1-golden.json`, produced once with
 * TweetNaCl before the switch to native libsodium) through the relay's
 * `crypto/sodium` facade: box, secretbox, Ed25519 and a sealed-sender envelope.
 * Any mismatch means the backend is not byte-compatible with every client in
 * the field. Never regenerate the fixture to make a failing test pass.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import tweetnacl from 'tweetnacl';
import naclUtil from 'tweetnacl-util';
import { nacl } from '../crypto/sodium/index.js';
import { verifyDetached } from '../crypto/ed25519.js';
import { openEnvelope, type SealedWire } from '../crypto/sealedSender.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE = path.resolve(HERE, '../../../mobile/src/crypto/__tests__/fixtures/f1-golden.json');
const b64 = naclUtil.encodeBase64;
const unb64 = naclUtil.decodeBase64;
const fill = (n: number, f: (i: number) => number): Uint8Array => Uint8Array.from({ length: n }, (_, i) => f(i) & 0xff);

// Same deterministic inputs as the mobile generator.
const A_SK = fill(32, (i) => i + 1);
const B_SK = fill(32, (i) => 0x80 + i);
const KEY = fill(32, (i) => 0x40 + i);
const NONCE = fill(24, (i) => 0xa0 + i);
const MSG_LENGTHS = [0, 1, 100, 1000];
const msg = (n: number): Uint8Array => fill(n, (i) => i * 7);

interface Golden {
  vectors: Record<string, string>;
  sealed: { recipientSeed: string; senderSeed: string; senderId: string; nowMs: number; payload: string; wire: SealedWire };
}

describe('F-1 golden fixtures (relay NaCl subset)', () => {
  const golden = JSON.parse(fs.readFileSync(FIXTURE, 'utf8')) as Golden;
  const v = golden.vectors;

  it('box / secretbox / Ed25519 reproduce the frozen bytes', () => {
    const bPk = unb64(v.bPk);
    const aPk = unb64(v.aPk);
    for (const n of MSG_LENGTHS) {
      expect(b64(nacl.box(msg(n), NONCE, bPk, A_SK))).toBe(v[`box_${n}`]);
      expect(nacl.box.open(unb64(v[`box_${n}`]), NONCE, aPk, B_SK)).toEqual(msg(n));
      expect(b64(nacl.secretbox(msg(n), NONCE, KEY))).toBe(v[`secretbox_${n}`]);
      expect(nacl.secretbox.open(unb64(v[`secretbox_${n}`]), NONCE, KEY)).toEqual(msg(n));
      expect(b64(nacl.sign.detached(msg(n), unb64(v.signSk)))).toBe(v[`sig_${n}`]);
      expect(verifyDetached(msg(n), unb64(v[`sig_${n}`]), unb64(v.signPk))).toBe(true);
    }
  });

  it('a frozen sealed-sender envelope still opens and authenticates', () => {
    const s = golden.sealed;
    const recipientSk = unb64(s.recipientSeed);
    // Key derivation from a seed is client-side only (not in the relay facade).
    const senderSignPk = tweetnacl.sign.keyPair.fromSeed(unb64(s.senderSeed)).publicKey;
    const opened = openEnvelope(s.wire, recipientSk, (from) => (from === s.senderId ? senderSignPk : null), s.nowMs);
    expect(opened).not.toBeNull();
    expect(opened!.from).toBe(s.senderId);
    expect(opened!.payload).toBe(s.payload);
  });
});
