#!/usr/bin/env bash
# infra/ssl/setup-ssl.sh — First-time SSL setup for AegisLink on AWS EC2
#
# Run once on the VM (as root or with sudo):
#   sudo bash /opt/aegislink/infra/ssl/setup-ssl.sh
#
# Prerequisites:
#   - aegislink.duckdns.org already resolves to this VM's public IP
#   - Relay is running via PM2 (port 3001 by default)
#   - Ports 80 and 443 are open in the AWS security group and iptables/firewalld
#
# Idempotent: safe to run multiple times.
# AegisLink privacy: nginx access_log is disabled — no user IPs are stored.

set -euo pipefail

DOMAIN="aegislink.duckdns.org"
CERTBOT_EMAIL="admin@aegislink.duckdns.org"
NGINX_CONF_DIR="/etc/nginx/sites-available"
NGINX_ENABLED_DIR="/etc/nginx/sites-enabled"
NGINX_CONF="$NGINX_CONF_DIR/aegislink"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"

log() { echo "[setup-ssl] $*"; }
err() { echo "[setup-ssl] ERROR: $*" >&2; exit 1; }

# ── Must run as root ────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  err "This script must be run as root (use: sudo bash setup-ssl.sh)"
fi

# ── 1. Install nginx if missing ─────────────────────────────────────────────
if ! command -v nginx &>/dev/null; then
  log "nginx not found — installing..."
  apt-get update -qq
  apt-get install -y nginx
  log "nginx installed."
else
  log "nginx already installed: $(nginx -v 2>&1)"
fi

# Ensure sites-available / sites-enabled directories exist (they do on Ubuntu
# but may be absent on minimal installs).
mkdir -p "$NGINX_CONF_DIR" "$NGINX_ENABLED_DIR"

# Make sure the default site is not overriding port 80 on our domain
if [[ -f "$NGINX_ENABLED_DIR/default" ]]; then
  log "Disabling default nginx site to avoid conflict..."
  rm -f "$NGINX_ENABLED_DIR/default"
fi

# ── 2. Install certbot if missing ───────────────────────────────────────────
if ! command -v certbot &>/dev/null; then
  log "certbot not found — installing..."
  apt-get update -qq
  apt-get install -y certbot python3-certbot-nginx
  log "certbot installed."
else
  log "certbot already installed: $(certbot --version 2>&1)"
fi

# ── 3. Write minimal HTTP-only config for domain verification ───────────────
log "Writing temporary HTTP config for certbot ACME challenge..."
cat > "$NGINX_CONF" <<'NGINX_TEMP'
server {
    listen 80;
    server_name aegislink.duckdns.org;

    # Certbot ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
NGINX_TEMP

# Enable site (idempotent — ln -sf overwrites existing symlink)
ln -sf "$NGINX_CONF" "$NGINX_ENABLED_DIR/aegislink"

# Test config before reloading
nginx -t
systemctl enable nginx
systemctl reload nginx || systemctl start nginx
log "nginx running with temporary config."

# ── 4. Obtain TLS certificate via certbot ───────────────────────────────────
# --keep-until-expiring makes this idempotent: certbot skips if cert is fresh.
log "Requesting Let's Encrypt certificate for $DOMAIN ..."
certbot certonly \
  --nginx \
  --non-interactive \
  --agree-tos \
  --email "$CERTBOT_EMAIL" \
  --domain "$DOMAIN" \
  --keep-until-expiring

log "Certificate obtained (or already up to date)."

# ── 5. Detect relay port from PM2 ───────────────────────────────────────────
RELAY_PORT="3001"  # safe default confirmed in server/package.json (PORT env)
if command -v pm2 &>/dev/null; then
  # pm2 env output includes PORT when set; fall back to 3001 if not found
  DETECTED_PORT=$(pm2 env aegislink-relay 2>/dev/null \
    | grep -E '^PORT\s*=' \
    | head -1 \
    | awk -F'=' '{print $2}' \
    | tr -d ' "' \
    || true)
  if [[ -n "$DETECTED_PORT" && "$DETECTED_PORT" =~ ^[0-9]+$ ]]; then
    RELAY_PORT="$DETECTED_PORT"
    log "Detected relay port from PM2: $RELAY_PORT"
  else
    log "Could not detect relay port from PM2 — using fallback: $RELAY_PORT"
  fi
else
  log "PM2 not found — using fallback relay port: $RELAY_PORT"
fi

# ── 6. Write final production nginx config ──────────────────────────────────
log "Writing production nginx config (proxy to relay on port $RELAY_PORT)..."
cat > "$NGINX_CONF" <<NGINX_PROD
# AegisLink — nginx production config
# Generated by infra/ssl/setup-ssl.sh
# Privacy: access_log is disabled — no user IPs are stored anywhere.

upstream aegis_relay {
    server 127.0.0.1:${RELAY_PORT};
}

server {
    listen 80;
    server_name ${DOMAIN};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    # Privacy: do NOT log client IPs or access patterns
    access_log off;
    error_log /var/log/nginx/aegislink-error.log warn;

    # Security headers
    add_header Strict-Transport-Security "max-age=63072000" always;
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header Referrer-Policy no-referrer;

    # WebSocket support — Socket.IO long-polling + upgrade
    location /socket.io/ {
        proxy_pass http://aegis_relay;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        # X-Real-IP forwarded to relay only — relay middleware discards it
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
        proxy_buffering off;
    }

    # REST API — all other routes
    location / {
        proxy_pass http://aegis_relay;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        # X-Real-IP forwarded to relay only — relay middleware discards it
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 60;
        proxy_send_timeout 60;
        proxy_buffering off;
        client_max_body_size 55M;
    }
}
NGINX_PROD

# Copy canonical version to project tree if project root is available
if [[ -d "$PROJECT_ROOT/infra/nginx" ]]; then
  cp "$NGINX_CONF" "$PROJECT_ROOT/infra/nginx/aegislink.conf"
  log "Config also saved to $PROJECT_ROOT/infra/nginx/aegislink.conf"
fi

nginx -t
systemctl reload nginx
log "nginx reloaded with production TLS config."

# ── 7. Install renewal cron ─────────────────────────────────────────────────
RENEW_SCRIPT="/opt/aegislink/infra/ssl/renew-ssl.sh"
CRON_JOB="0 3 * * * $RENEW_SCRIPT >> /var/log/aegislink-ssl-renew.log 2>&1"

if [[ -f "$RENEW_SCRIPT" ]]; then
  # Add cron entry if not already present
  if ! crontab -l 2>/dev/null | grep -qF "$RENEW_SCRIPT"; then
    (crontab -l 2>/dev/null; echo "$CRON_JOB") | crontab -
    log "Renewal cron job added: $CRON_JOB"
  else
    log "Renewal cron job already present."
  fi
else
  log "WARNING: $RENEW_SCRIPT not found — add renewal cron manually."
fi

# ── 8. Final health check ────────────────────────────────────────────────────
log "Running health check against https://$DOMAIN/health ..."
MAX_RETRIES=6
RETRY_INTERVAL=5
for i in $(seq 1 $MAX_RETRIES); do
  HTTP_CODE=$(curl --silent --output /dev/null --write-out '%{http_code}' \
    --max-time 10 "https://$DOMAIN/health" || true)
  if [[ "$HTTP_CODE" == "200" ]]; then
    log "Health check PASSED (HTTP 200)."
    break
  fi
  if [[ $i -eq $MAX_RETRIES ]]; then
    err "Health check FAILED after $((MAX_RETRIES * RETRY_INTERVAL))s — last HTTP code: $HTTP_CODE. Check relay is running (pm2 status)."
  fi
  log "Attempt $i/$MAX_RETRIES — HTTP $HTTP_CODE — retrying in ${RETRY_INTERVAL}s..."
  sleep "$RETRY_INTERVAL"
done

log "SSL setup complete. https://$DOMAIN is live."
log "Certificate auto-renewal: daily cron at 03:00 via $RENEW_SCRIPT"
