/**
 * torBridges — how the embedded Tor reaches the Tor network when the local
 * network blocks it (pluggable transports / bridges).
 *
 * Tor always-on (docs/SEALED-SENDER-ARCHITECTURE.md §6.2) means there is no
 * clearnet fallback. So on a network that blocks Tor, the app can only connect
 * through a bridge. This module is the platform-independent core, kept
 * byte-identical in logic with desktop/src/main/tor/bridges.ts. The native layers
 * only run the transport and apply the torrc lines this module produces.
 *
 *   - Built-in bridges are Tor Browser's own (`builtinBridges.json`, generated by
 *     scripts/sync-tor-bridges.mjs from the pinned Tor Expert Bundle's
 *     pt_config.json).
 *   - "auto" (the default) starts direct and escalates when the bootstrap stalls:
 *     direct → snowflake → obfs4 → meek (Tor Browser's "connection assist"
 *     order, minus Conjure). The transport that worked is remembered locally.
 *   - "custom" uses lines the user pasted (bridges.torproject.org, the
 *     @GetBridgesBot Telegram bot, a friend). They are validated STRICTLY: they
 *     become torrc / SETCONF input, so any character that could close a value
 *     or start a new directive (newline, quote, `#`, `\`) is rejected, never
 *     escaped.
 */
import BUILTIN from './builtinBridges.json';

export type TorTransport = 'direct' | 'snowflake' | 'obfs4' | 'meek' | 'custom';
export type TorConnectionMode = 'auto' | TorTransport;

/** Pluggable-transport protocol names as tor knows them. */
export type PtName = 'obfs4' | 'webtunnel' | 'snowflake' | 'meek_lite';
export const SUPPORTED_PTS: readonly PtName[] = ['obfs4', 'webtunnel', 'snowflake', 'meek_lite'];

/** Escalation order for "auto". */
export const AUTO_ORDER: readonly TorTransport[] = ['direct', 'snowflake', 'obfs4', 'meek'];

export const CONNECTION_MODES: readonly TorConnectionMode[] = ['auto', 'direct', 'snowflake', 'obfs4', 'meek', 'custom'];

/** At most this many custom bridge lines are kept. */
export const MAX_CUSTOM_BRIDGES = 20;
const MAX_LINE_LENGTH = 1500;

/**
 * Bootstrap watchdog, calibrated on real bootstraps (2026-09-23, desktop tor
 * 15.0.23). Snowflake reached 100% in 51s. obfs4 took 123s, sitting ~100s at 50%
 * ("loading relay descriptors") with no progress line while the directory
 * trickled through the bridge. So silence means "blocked" only BEFORE the first
 * hop answers. Once connected, a transport gets far longer before auto moves on.
 */
/** Below this progress, tor has not reached its first hop (guard or bridge) yet. */
export const FIRST_HOP_PROGRESS = 15;
/** No progress for this long before the first hop → blocked. */
export const STALL_NO_PROGRESS_MS = 30_000;
/** No progress for this long after the first hop answered → stalled. */
export const STALL_CONNECTED_NO_PROGRESS_MS = 150_000;
/** Not connected after this long on one transport → stalled. */
export const STALL_TOTAL_MS = 300_000;

interface BuiltinFile { source: string; bridges: { obfs4: string[]; snowflake: string[]; meek: string[] } }
const builtin = BUILTIN as BuiltinFile;

export function isConnectionMode(v: unknown): v is TorConnectionMode {
  return typeof v === 'string' && (CONNECTION_MODES as readonly string[]).includes(v);
}

// One bridge line: an optional transport, an address (IPv4:port or [IPv6]:port),
// an optional 40-hex fingerprint, then key=value arguments. Only characters that
// real bridge lines use (base64, URLs, host lists) are allowed.
const ADDR = String.raw`(?:\d{1,3}(?:\.\d{1,3}){3}|\[[0-9A-Fa-f:.]+\]):\d{1,5}`;
const ARG = String.raw`[A-Za-z0-9_-]+=[A-Za-z0-9+/=:.,_\-~%?&@\[\]]+`;
const LINE_RE = new RegExp(
  String.raw`^(?:(obfs4|webtunnel|snowflake|meek_lite)\s+)?${ADDR}(?:\s+[0-9A-Fa-f]{40})?(?:\s+${ARG})*$`,
);

/** The PT a (validated) line needs, or null for a vanilla bridge. */
export function ptOfLine(line: string): PtName | null {
  const first = line.split(/\s+/, 1)[0];
  return (SUPPORTED_PTS as readonly string[]).includes(first) ? (first as PtName) : null;
}

/** Normalise and validate ONE bridge line; null if it is not a bridge line we accept. */
export function normalizeBridgeLine(raw: string): string | null {
  let line = raw.trim();
  if (/^bridge\s+/i.test(line)) line = line.replace(/^bridge\s+/i, '');
  line = line.replace(/[ \t]+/g, ' ');
  if (line.length === 0 || line.length > MAX_LINE_LENGTH) return null;
  // Anything able to break out of a torrc / SETCONF value is refused outright.
  if (/[\r\n"'#\\\u0000-\u001f\u007f]/.test(line)) return null;
  return LINE_RE.test(line) ? line : null;
}

/**
 * Parse what the user pasted (one bridge per line, `Bridge ` prefix optional,
 * blank lines and `#` comments ignored). Returns the valid lines (deduplicated,
 * capped at MAX_CUSTOM_BRIDGES) and how many non-empty lines were rejected.
 */
export function parseBridgeLines(text: string): { lines: string[]; rejected: number } {
  const lines: string[] = [];
  let rejected = 0;
  for (const raw of text.split(/\r?\n/)) {
    const t = raw.trim();
    if (t === '' || t.startsWith('#')) continue;
    const ok = normalizeBridgeLine(t);
    if (!ok) { rejected++; continue; }
    if (!lines.includes(ok) && lines.length < MAX_CUSTOM_BRIDGES) lines.push(ok);
  }
  return { lines, rejected };
}

/** Bridge lines (without the `Bridge ` keyword) to use for a transport. [] = direct. */
export function bridgeLinesFor(transport: TorTransport, custom: readonly string[] = []): string[] {
  switch (transport) {
    case 'direct': return [];
    case 'snowflake': return [...builtin.bridges.snowflake];
    case 'obfs4': return [...builtin.bridges.obfs4];
    case 'meek': return [...builtin.bridges.meek];
    case 'custom': return custom.map(normalizeBridgeLine).filter((l): l is string => l !== null);
  }
}

/** The pluggable transports `lines` need (each started once). */
export function ptsNeeded(lines: readonly string[]): PtName[] {
  const out: PtName[] = [];
  for (const l of lines) {
    const pt = ptOfLine(l);
    if (pt && !out.includes(pt)) out.push(pt);
  }
  return out;
}

/**
 * The torrc lines for a set of bridges, given how each PT is reached
 * (`ClientTransportPlugin` value per PT — `socks5 127.0.0.1:<port>` for a
 * managed IPtProxy transport on mobile, `exec <path>` on desktop). Returns
 * `['UseBridges 0']` for direct. A PT without a plugin value makes the whole
 * config fail CLOSED (null): tor would otherwise ignore those bridges.
 */
export function torrcFor(lines: readonly string[], plugin: Partial<Record<PtName, string>>): string[] | null {
  if (lines.length === 0) return ['UseBridges 0'];
  const out: string[] = [];
  for (const pt of ptsNeeded(lines)) {
    const how = plugin[pt];
    if (!how) return null;
    out.push(`ClientTransportPlugin ${pt} ${how}`);
  }
  for (const l of lines) out.push(`Bridge ${l}`);
  out.push('UseBridges 1');
  return out;
}

/** "auto": the transport to try after `current` stalled; null when all were tried. */
export function nextAutoTransport(current: TorTransport): TorTransport | null {
  const i = AUTO_ORDER.indexOf(current);
  return i >= 0 && i + 1 < AUTO_ORDER.length ? AUTO_ORDER[i + 1] : null;
}

/** First transport for a mode ("auto" starts from the last one that worked). */
export function initialTransport(mode: TorConnectionMode, lastWorking: TorTransport | null): TorTransport {
  if (mode !== 'auto') return mode;
  return lastWorking && AUTO_ORDER.includes(lastWorking) ? lastWorking : 'direct';
}

/** Bootstrap watchdog verdict. */
export function isBootstrapStalled(s: { startedAt: number; lastProgressAt: number; progress: number; now: number }): boolean {
  if (s.progress >= 100) return false;
  const quietLimit = s.progress < FIRST_HOP_PROGRESS ? STALL_NO_PROGRESS_MS : STALL_CONNECTED_NO_PROGRESS_MS;
  return s.now - s.lastProgressAt > quietLimit || s.now - s.startedAt > STALL_TOTAL_MS;
}

/** Provenance of the built-in list (shown nowhere; kept for audits). */
export const BUILTIN_BRIDGES_SOURCE: string = builtin.source;
